spring.application.name=academia-idiomas-api

# Carga la configuración local desde .env
spring.config.import=optional:file:.env[.properties]

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:academia_idiomas}
spring.datasource.username=${POSTGRES_USER:academia_user}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true